### PR TITLE
PXBLUE-2519 Changed pxb references to blui

### PR DESCRIPTION
**Pull request by bkarambe**
Fixes # PXBLUE-2519

#### Changes proposed in this Pull Request:
- pxb ==> blue

### CODE REVIEW

**Review by emclaug2 — COMMENTED** [review]
I think it looks good to me, I'm a little iffy on changing the PXB refs for past releases since Brightlayer UI didn't exist yet.  I'd treat this similar to how we handled our changelogs, for previous references to @pxblue, we kept them.

**Comment by emclaug2** [comment]
I'd appreciate someone else input on this though.

**Comment by jeffvg** [comment]
I agree with @emclaug2  R16 through R22 should reflect pxblue

**Comment by huayunh** [comment]
That makes me wonder... 

Should https://brightlayer-ui-dev.github.io/release-notes also consistently use `PX Blue` prior to R22?

**Comment by andrupu** [comment]
I agree with @emclaug2, we should handle it like our other Changelogs, keeping the past PXBlue refs in place and make a new entry for the BLUI Rebrand.
image

Looks like we already have the new entry for the BLUI Rebrand in R22 Roadmap good to go.  Might want to have "author: 'PXBlue' " for the past entries up to R22.  Anything in R23 is already looking good with "author: 'Brightlayer UI' ".

**Comment by emclaug2** [comment]
@bkarambe Please revert the BLUI migration for R16 - R21.  R22 can stay as BLUI.  

The doc-it release page will be separate discussion; I still think it's fine as-is since if we partially reverted it, some resources would be referred to as 'PX Blue' but any links would reference BLUI resources.  I think the inconsistency could cause more confusion.

**Comment by bkarambe** [comment]
> @bkarambe Please revert the BLUI migration for R16 - R21. R22 can stay as BLUI.
> 
> The doc-it release page will be separate discussion; I still think it's fine as-is since if we partially reverted it, some resources would be referred to as 'PX Blue' but any links would reference BLUI resources. I think the inconsistency could cause more confusion.

Done

**Review by daileytj — APPROVED** [review]

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
